# Generated by Django 2.0.6 on 2021-08-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('pk_autores', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('pk_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='editoriales',
            fields=[
                ('pk_editoriales', models.AutoField(primary_key=True, serialize=False)),
                ('editorial', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('pk_libros', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fk_autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.autores')),
                ('fk_categorias', models.ManyToManyField(to='BookStore.categorias')),
                ('fk_editoriales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.editoriales')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fk_product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_product',
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
