# Generated by Django 2.0.6 on 2021-09-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_libros_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autores',
            options={'ordering': ['autor'], 'verbose_name': 'autores', 'verbose_name_plural': 'autores'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['categoria'], 'verbose_name': 'categorias', 'verbose_name_plural': 'categoriass'},
        ),
        migrations.AlterModelOptions(
            name='editoriales',
            options={'ordering': ['editorial'], 'verbose_name': 'editoriales', 'verbose_name_plural': 'editorialess'},
        ),
        migrations.AlterModelOptions(
            name='libros',
            options={'ordering': ['titulo'], 'verbose_name': 'libros', 'verbose_name_plural': 'libross'},
        ),
        migrations.AddField(
            model_name='libros',
            name='linklibro',
            field=models.URLField(default='https://drive.google.com/file/d/1B7iR9cTTGjD3pbo5gVvq0liIdkTBTIs9/view?usp=sharing', max_length=8000),
        ),
    ]
