# Generated by Django 2.0.6 on 2021-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0005_remove_libros_linklibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='linklibro',
            field=models.URLField(default='https://drive.google.com/file/d/1B7iR9cTTGjD3pbo5gVvq0liIdkTBTIs9/view?usp=sharing', max_length=8000),
        ),
    ]
