# Generated by Django 2.0.6 on 2021-09-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0006_libros_linklibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='paginas',
            field=models.IntegerField(default=1),
        ),
    ]
