# Generated by Django 2.0.6 on 2021-09-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0006_libros_linklibro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='paginas',
        ),
    ]
